---

kind: Template
apiVersion: v1
metadata:
  name: pysimple
  annotations:
    description: The PySimple Exercise Application (Route)
labels:
  template: pysimple

# ----------
# Parameters
# ----------

parameters:

- name: NAMESPACE
  value: pysimple

- name: SERVICE_NAME
  value: pysimple

# -------
# Objects
# -------

objects:

- kind: Route
  apiVersion: v1
  metadata:
    name: pysimple
    namespace: ${NAMESPACE}
  spec:
    port:
      targetPort: http
    to:
      kind: Service
      name: ${SERVICE_NAME}
