---

# Template for the user's PV.
# Replace %DIR% with the export directory.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-%DIR%
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /exports/%DIR%
    server: cloudv199.zdv.uni-mainz.de
  persistentVolumeReclaimPolicy: Recycle
