---

kind: Template
apiVersion: v1
metadata:
  name: pysimple
  annotations:
    description: The PySimple Exercise Application (Deployment Configuration)
labels:
  template: pysimple

# ----------
# Parameters
# ----------

parameters:

- name: NAME
  value: pysimple

- name: NAMESPACE
  value: pysimple

- name: IMAGE
  value: alanbchristie/pysimple:2019.2

# -------
# Objects
# -------

objects:

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    template:
      metadata:
        labels:
          name: ${NAME}
      spec:
        containers:
        - image: ${IMAGE}
          name: ${NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          # Ideally, define container (Pod) resources
          # i.e. memory and CPU expectations...
          resources:
            limits:
              cpu: 1000m
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 8Mi
          # Ideally, define container probes.
          # Used by Kubernetes to determine Pod health...
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3