---

kind: Template
apiVersion: v1
metadata:
  name: pysimple
  annotations:
    description: The PySimple Exercise Application (Persistent Volume Claim)
labels:
  template: pysimple

# ----------
# Parameters
# ----------

parameters:

- name: NAMESPACE
  value: pysimple

- name: STORAGE_SIZE
  value: 1Gi

# ----------
# Parameters
# ----------

objects:

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: pysimple
    namespace: ${NAMESPACE}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${STORAGE_SIZE}
